#!/usr/bin/env bash

#set -x -T

attendance_file='/home/skondamalla/Videos/report.txt'
breaktime_file='/home/skondamalla/Videos/biometric.txt'
break_counter=0

function search() {
	local FUNC=search
	search_string="$1"
	e="$2"

	shift
	for e; do [[ "$e" == "$search_string" ]] && return 0; done
	return 1
}

IFS=$'\n'
attendance=( $(cat $attendance_file | tr " " ",") )
breaktime=( $(cat $breaktime_file | tr "\t" ",") )

if [[ ${#attendance[@]} -gt 0 && ${#breaktime[@]} -gt 0 ]]; then
#	echo -e "Attendance records:\t" ${#attendance[@]}
#	echo -e "BreakTime records:\t" ${#breaktime[@]}

	for ((a=0; a<${#breaktime[@]}; a++))
	do
		breaktime_id+=( $( echo ${breaktime[$a]} | awk -F"," '{print $1}') )
	done

	#echo -e "Total records in BreakTime-ID's:\t" ${#breaktime_id[@]}

	for ((i=0; i<${#attendance[@]}; i++))
	do
		attendance_record=$( echo ${attendance[$i]} | awk -F"," '{print $1}' )
		if [[ $(search "$attendance_record" "${breaktime_id[@]}"; echo $?) -eq 0 ]]; then
#			echo -e "${attendance[$i]} has a break time..."
			breaktime_record=$( echo ${breaktime[$break_counter]} | awk -F"," '{print $2}' )
#			echo -e "BreakTime record:\t"$breaktime_record
			all_attendance+=( ${attendance[$i]}","$breaktime_record )
#			echo ${#all_attendance[@]}
			break_counter=`expr $break_counter + 1`
		else
#			echo -e "${attendance[$i]} doesnot have a in BreakTime..."
			all_attendance+=( ${attendance[$i]}",00:00" )
		fi
	done
	for ((b=0; b<${#all_attendance[@]}; b++))
	do
		echo -e ${all_attendance[$b]}
	done
else
	echo -e "Someting went wrong in fetching attendance and breaktime records..."
fi
